# Generated by Django 5.0.3 on 2024-03-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(blank=True, null=True, to='movies.actor', verbose_name='В главных ролях'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, null=True, to='movies.director', verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='movies.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='premiere',
            field=models.DateField(blank=True, null=True, verbose_name='Премьера'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screenwriter',
            field=models.ManyToManyField(blank=True, null=True, to='movies.screenwriter', verbose_name='Сценарист'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='time',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Год производства'),
        ),
    ]
