# Generated by Django 5.0.3 on 2024-03-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_actor_alter_movie_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на трейлер'),
        ),
    ]
